### ISSUE TITLE
How can the dotted line be adjusted on the Y axis?

### ISSUE THREAD

**Issue by tciuro** [dagronf/DSFSparkline#1]
I'd like to adjust the dotted line, as seen in the Crash graph here:

https://raw.githubusercontent.com/dagronf/dagronf.github.io/master/art/projects/DSFSparkline/DSFSparkline_light.png

I haven't been able to see how it can be done. Thanks!

**Comment by dagronf** [comment]
Hi there!

You can set 'showZero = true' on the sparkline object to show the zero value.  If you are using Interface Builder, you should be able to find a 'Show Zero' inspectable for showing the line.

At the moment, the only horizontal line that can be shown is the zero line (which means it will only show if you have -ve -> +ve range).

Cheers -- let me know if you're still having issues with this.

Darren.

**Comment by dagronf** [comment]
If you need to change that it shows a value other than zero, you can find the code for displaying the line here :-

https://github.com/dagronf/DSFSparkline/blob/2608f088590d222223a09a610947361e2061dc4b/Sources/DSFSparkline/private/ui/DSFSparklineView.swift#L149

If you do change the code to allow it to show a line not at zero, please don't be afraid to put up a patch - it's something that would definitely make the library better!

**Comment by dagronf** [comment]
Hi there,

If you look at the latest version (3.0.0) you'll see a new member variable on the datasource called `zeroLineValue` where you can set where the zero line draws (this defaults to 0.0 to keep backwards compatibility).

So, if the range is 0 -> 100 and you want the line to draw at 85 then just set `zeroLineValue` to 85 on the datasource.  You can dynamically change this value if you want (ie. changing the value will automatically update the graph to match).  This will work for SwiftUI too.

Let me know if you have any issue with it.

**Comment by tciuro** [comment]
Hello Darren! Thank you for your prompt reply! I will spend some time today working on this. In SwiftUI, there is also the case where a `List` selection leaves a rectangle around the graph. I'll see if setting the color to `.clear` honors the background, allowing it to blend better with its surroundings.

I'll follow your lead from your comments above and see if it works. If not, let's see if I can find a fix :-) I'll keep you posted.

Cheers!

**Comment by tciuro** [comment]
A new finding in `3.0.0.` unrelated to the discussed above. In `SparklineWindow.swift` line `68`:

`Cannot find type 'CGFloat' in scope; did you mean to use 'CGFloat'?`

Super weird. I solved it by adding `import CoreGraphics`. This happens on `Xcode 12.3`.

**Comment by tciuro** [comment]
So, in version `3.0.0` the `zeroLineValue` property works as advertised. Excellent. I have added a few properties to further control the `zero line`. Example:

    self.sparklineDatapoints.zeroLineColor = UIColor.systemGreen
    self.sparklineDatapoints.zeroLineWidth = 2
    self.sparklineDatapoints.zeroLineStyle = [3, 4]

I find it gives better control to contrast the line against certain backgrounds. I will propose a patch shortly.

Cheers, Darren.

**Comment by dagronf** [comment]
Fixed for these issues and the ability to 

1. configure to the drawing style for the zero-line
2. reposition the 'zero line' to a non-zero value

have been added to 3.1.0

**Comment by tciuro** [comment]
Thanks a lot, Darren. We can close this issue. Cheers!
