### ISSUE TITLE
Breaks SwiftUI Previews

### ISSUE THREAD

**Issue by kmkarim** [dagronf/DSFSparkline#10]
When adding DSKSparkline to a swift project the following error occurs in SwiftUI previews:

```
HumanReadableSwiftError

SettingsError: noExecutablePath(<IDESwiftPackageStaticLibraryProductBuildable:ObjectIdentifier(0x000060000054f960):'DSFSparkline'>)
```

**Comment by dagronf** [comment]
See: https://github.com/dagronf/QRCode/issues/5

**Comment by dagronf** [comment]
A new version 4.5.0 is available -- if you update your package(s) you should get the new version.

This new version :-

* Defaults to a non-specified library type for the `DSFSparkline` package
* Provides explicit static/shared library instances IF you need them. Note that linking against either of these will still break SwiftUI previews until Xcode fixes the issue on their side.

**Comment by dagronf** [comment]
@kmkarim did this fix your issue?

**Comment by dagronf** [comment]
Closed due to inactivity and lack of feedback. 4.5.0 should help with this.
