### ISSUE TITLE
UIKIT for this chart

### ISSUE THREAD

**Issue by ahmedsafadii** [dagronf/DSFSparkline#11]
![image](https://user-images.githubusercontent.com/6974081/200678948-a54ed8ce-6f84-497c-9749-f390f8a77fd1.png)

I really need the code for this chart exactly static without animation, I try everything but not getting close ;(

@dagronf 

I want it to fill the view

**Comment by ahmedsafadii** [comment]
<img width="1388" alt="Screenshot 2022-11-09 at 12 33 02 AM" src="https://user-images.githubusercontent.com/6974081/200680202-8b84eaee-cd60-4ae7-a397-ac4a2228b093.png">

This is what i got

**Comment by ahmedsafadii** [comment]
<img width="904" alt="Screenshot 2022-11-09 at 12 33 19 AM" src="https://user-images.githubusercontent.com/6974081/200680231-af329a1f-a7a4-4b13-8ae2-73d97e05eb14.png">

This is the example that I'm trying to do

**Comment by ahmedsafadii** [comment]
@dagronf Thank you for the example but it didn't fill the width that I'm using for example

I have this
<img width="293" alt="Screenshot 2022-11-09 at 9 07 00 AM" src="https://user-images.githubusercontent.com/6974081/200752525-233624b1-eb2d-461a-a65a-fab93379bca4.png">

100px x 36px

the result it 

<img width="63" alt="Screenshot 2022-11-09 at 9 07 19 AM" src="https://user-images.githubusercontent.com/6974081/200752574-14bbc215-56f7-4a5c-9a7f-2ed0a4396940.png">

Note that I only use 6 values I need, so if they're at least equal width, to fill the width that I set in the constraint

0.72, 0.84, 0.15, 0.16, 0.30, 0.58

**Comment by dagronf** [comment]
You’ve set the window size in the data source to 30, but you’re only providing 6 values.

try setting the window size to 6?

**Comment by dagronf** [comment]
My interface builder layout looks like this...

![image](https://user-images.githubusercontent.com/2636615/200763678-45d129b8-efa6-48a6-8477-c0593cf1a74b.png)

**Comment by ahmedsafadii** [comment]
Big hug and thanks for you <3 <3.

I would say that this library it's not the only one that supports swift UI and swift, it's actually more cool and stable than the charts which are huge.

Thank you it was my issue 

<img width="265" alt="Screenshot 2022-11-09 at 10 17 49 AM" src="https://user-images.githubusercontent.com/6974081/200764265-2cf1efb9-a8f7-4526-867f-15005f3f68cd.png">

I had to remove 30 from here.

Thank you again

**Comment by dagronf** [comment]
My pleasure mate. I'm glad we were able to sort it out!
