### ISSUE TITLE
Animations on push navigation

### ISSUE THREAD

**Issue by sepehr-keyhani** [dagronf/DSFSparkline#12]
When I use DSFSparkline on my view, push navigation will not work with animation.

**Comment by dagronf** [comment]
Can you add some more info to this? I have no understanding of the issue you’re seeing.

even better - can you attach a sample project that shows the problem?

**Comment by dagronf** [comment]
Update to the latest version (4.5.1) which may solve your issue.

**Comment by sepehr-keyhani** [comment]
> Update to the latest version (4.5.1) which may solve your issue.

Thank you, fixed!
