### ISSUE TITLE
Publish tags to Cocoapods

### ISSUE THREAD

**Issue by GregOriol** [dagronf/DSFSparkline#15]
Hi @dagronf,

Thanks for the great library!

Could you publish the version tags to Cocoapods so we can keep track of the version being used? currently installing the master prevents knowing easily what we are integrating and may cause issues if any breaking changes are introduced.

**Comment by dagronf** [comment]
@GregOriol I've just pushed up a new tag 5.2.3 which is now synchronized on Cocoapods. It has no changes other than to sync cocoapods (well, and a minor documentation update).

Apologies for that! Please let me know if you're still having issues.

**Comment by dagronf** [comment]
Ah. I think I misunderstood your problem.

**Comment by dagronf** [comment]
@GregOriol Okay I think I've fixed the issue. The source specified in the podspec didn't contain a valid :git entry

I've updated the podspec (and tagged the branch to 5.2.4) and it appears to working as expected (ie. `pod 'DSFSparkline', '~> 5.2.4'` pulls down the expected version and integrates it.

Can you please check this works for you?  Thanks!

**Comment by dagronf** [comment]
(Oh and apologies for accidentally closing the issue before!)

**Comment by GregOriol** [comment]
@dagronf Thanks, it works now with a tag configuration in the Podfile like `pod 'DSFSparkline', '~> 5.2'`
