### ISSUE TITLE
Cannot find type 'NSTextAttachment' in scope" crashes when using SwiftPackage

### ISSUE THREAD

**Issue by BlackBird-One** [dagronf/DSFSparkline#5]
Hi, 
DFSSparkLine cannot be built into a purely SwiftUI application with SwiftPackage.

When the DFSSparkLine package is added to the application, the compilation crashes with the error "DSFSparklineSurface + AttributedString.swift: 84: 83: Cannot find type 'NSTextAttachment' in scope"

**Comment by dagronf** [comment]
Thanks for the heads up mate.  I’ll take a look as soon as I can.

**Comment by dagronf** [comment]
Hey mate - I found the issue (I'd forgotten to add an import in the AttributedString code). Ive tested it locally and pushed a new version of the library up (4.1.2).  Would you updating to the latest and checking that the issue has been resolved?

Thanks!

**Comment by dagronf** [comment]
Okay given I haven't heard anything I'm going to assume that everything was fixed.
