### ISSUE TITLE
feature: insert at in addition to push

### ISSUE THREAD

**Issue by PierreBrisorgueil** [dagronf/DSFSparkline#7]
hey, is it possible to update an index of the datasource in the dot graph in addition to the push? this would generate other types of filling animations ?

**Comment by dagronf** [comment]
Hey mate, there's currently no direct way to update a value in a datasource, the library only allows you to push or set.

However, you could simulate it yourself using a set if you wanted!

```swift
   let source = DSFSparkline.DataSource(values: [0,1,2,3,4,5,6,7])

   // Do something...

   var currentData = source.data
   currentData.replaceSubrange(3...3, with: [33])
   source.set(values: currentData)
   Swift.print(source)
```

**Comment by PierreBrisorgueil** [comment]
Hum, okok, Nice ! 👌

Thx for your time and reactivity !
