### ISSUE TITLE
Crash when moving window from monitor with regular scale to retina scale and vice versa

### ISSUE THREAD

**Issue by joekw** [dagronf/DSFSparkline#9]
When moving my window with a few `DSFSparklineLineGraphView` in it on macOS 12.4 from a standard scale monitor, to a retina scale monitor, the app crashes.

```
DSFSparkline/DSFSparklineOverlay+RangeHighlight.swift:29: Fatal error: Use of unimplemented initializer 'init(layer:)' for class 'DSFSparkline.RangeHighlight'
```

It appears to crash on the `l.contentsScale = scale` line within `RendererDelegate`.
```
	func draw(_ layer: CALayer, in ctx: CGContext) {
		if let l = layer as? DSFSparklineOverlay {
			let scale = view.retinaScale()
			l.contentsScale = scale
			let insetBounds = view.edgeInsets(for: view.bounds)
			l.drawGraph(context: ctx, bounds: view.bounds.inset(by: insetBounds), scale: scale)
		}
	}
```

**Comment by dagronf** [comment]
Hi there!

Thank you for reporting this. Unfortunately I don't have a non-retina display to test against, however I'm pretty sure this relates to the fact that I've didn't add init(layer:...) methods on the classes that inherit from CALayer(). That'll teach me for being a lazy programmer.

I've made some changes to the code to add init(layer:...) functions to prove this hypothesis, however without a non-retina display to test with I'm in a bit of a bind with testing.

I've added the changes to a new branch (called `issue_9_fix`) within this repo - I was wondering whether you could re-build your code against this new branch and verify whether the issue has been solved? If you can't reproduce the issue with the new branch code I'll move it across into `main`.

Many thanks!

**Comment by dagronf** [comment]
Ah I discovered a way to test this - and I was able to reproduce the issue on `main`!

Installing EasyRes from the App Store (https://apps.apple.com/au/app/easyres/id688211836?mt=12) I was able to toggle my iMac's retina display to a non-retina display, which triggered the issue.

The `issue_9_fix` branch appears to solve this issue - but I'd really like to get your feedback before merging onto `main`

**Comment by dagronf** [comment]
Actually, I'm certain that I was able to reproduce the issue you were seeing.  After making these changes I was able to resolve the crash - which means it was worthy to include in main regardless of whether your issue is ultimately fixed.

If you update to v4.4.0 on main you will get these fixes. Please let me know if you're still seeing the issue.

**Comment by joekw** [comment]
Wow, that has to be the shortest time from bug report to fix i've ever experienced. All good over here, thanks a lot!

**Comment by dagronf** [comment]
Ah that's good news mate. Sorry for the inconvenience!
